Make testing use numbers with a step
Instead of using completely random floating numbers, use stepped ones as this helps catch some interesting edge cases when those numbers start overlap.

E.g. with this change getting right away:
```
---- tests::test_nearests stdout ----
thread 'tests::test_nearests' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `5`', src\tests.rs:35:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(fixes are not included in this PR)